### ISSUE TITLE
makeQuotes() for each loop not adding last quote to quoteElements List

### ISSUE THREAD

**Issue by samWson** [samWson/quote-inspiration#1]
In file quotes.QuoteImporter.java starting at line 88.

This section of code is not adding the very last group of lines (Making up a single quote) to the quoteElements List. 

Groups of lines are separated by a single blank line i.e. an empty String (""). These groups of lines make up the fields of a Quote object.

The final line is not an empty String (""), therefore add() is never reached and the last group of lines never gets added to quoteElements.

Need to find a way of making the for each loop detect the last String in lines so it can be added to quoteElements.
```
    List<String> singleQuote = new ArrayList<>();
	
	for (String line: lines) {

	    singleQuote.add(line);

	    /* If a blank line is added, that is the end of the
	       Quote. Add it to the quoteElements List.
	    */
	    if (line.equals("")) {

		quoteElements.add(new ArrayList<String>(singleQuote));

		// Clear the List, making it ready for a new series of
		// Quote elements.
		singleQuote.clear();
	    }
    }
```

**Comment by c17a** [comment]
What about manually adding an empty string to the lines Array before the loop? 

```
List<String> singleQuote = new ArrayList<>();
	
        lines.add("");//manually add empty string to the end of the lines array

	for (String line: lines) {

	    singleQuote.add(line);

	    /* If a blank line is added, that is the end of the
	       Quote. Add it to the quoteElements List.
	    */
	    if (line.equals("")) {

		quoteElements.add(new ArrayList<String>(singleQuote));

		// Clear the List, making it ready for a new series of
		// Quote elements.
		singleQuote.clear();
	    }
    }
```

**Comment by samWson** [comment]
@genericmethod Thanks for the suggestion. Since lines was a String[] I had to make a new ArrayList<String> first, but your suggestion worked just fine. Thanks for the help.

**Comment by c17a** [comment]
Yepp you're right, missed that ✅
